#!/usr/bin/env python3
"""
Generate 3000 realistic email addresses with randomized domains and names.
"""

import random
import string

# Lists of realistic first and last names
first_names = [
    'john',
    'jane',
    'michael',
    'sarah',
    'david',
    'lisa',
    'robert',
    'mary',
    'james',
    'patricia',
    'william',
    'jennifer',
    'richard',
    'linda',
    'joseph',
    'elizabeth',
    'thomas',
    'barbara',
    'charles',
    'susan',
    'christopher',
    'jessica',
    'daniel',
    'margaret',
    'matthew',
    'karen',
    'anthony',
    'nancy',
    'mark',
    'betty',
    'donald',
    'helen',
    'steven',
    'sandra',
    'paul',
    'donna',
    'andrew',
    'carol',
    'joshua',
    'ruth',
    'kenneth',
    'sharon',
    'kevin',
    'michelle',
    'brian',
    'laura',
    'george',
    'emily',
    'edward',
    'kimberly',
    'ronald',
    'deborah',
    'timothy',
    'dorothy',
    'jason',
    'amy',
    'jeffrey',
    'angela',
    'ryan',
    'brenda',
    'jacob',
    'emma',
    'gary',
    'olivia',
    'nicholas',
    'cynthia',
    'eric',
    'marie',
    'jonathan',
    'janet',
    'stephen',
    'catherine',
    'larry',
    'frances',
    'justin',
    'samantha',
    'scott',
    'debra',
    'brandon',
    'rachel',
    'benjamin',
    'carolyn',
    'samuel',
    'janet',
    'gregory',
    'virginia',
    'frank',
    'maria',
    'raymond',
    'heather',
    'alexander',
    'diane',
    'patrick',
    'julie',
    'jack',
    'joyce',
    'dennis',
    'victoria',
    'jerry',
    'kelly',
    'tyler',
    'christina',
    'aaron',
    'joan',
    'henry',
    'evelyn',
    'douglas',
    'lauren',
    'nathan',
    'judith',
    'peter',
    'megan',
    'zachary',
    'cheryl',
    'kyle',
    'andrea',
    'noah',
    'hannah',
    'william',
    'jacqueline',
    'caleb',
    'martha',
    'mason',
    'gloria',
    'eli',
    'teresa',
    'lucas',
    'sara',
    'elijah',
    'janice',
    'owen',
    'marie',
    'liam',
    'julia',
    'isaac',
    'kathryn',
    'wyatt',
    'frances',
    'hunter',
    'annie',
    'evan',
    'alice',
    'connor',
    'lois',
    'carter',
    'katherine',
    'adrian',
    'louise',
    'alex',
    'anna',
]

last_names = [
    'smith',
    'johnson',
    'williams',
    'brown',
    'jones',
    'garcia',
    'miller',
    'davis',
    'rodriguez',
    'martinez',
    'hernandez',
    'lopez',
    'gonzalez',
    'wilson',
    'anderson',
    'thomas',
    'taylor',
    'moore',
    'jackson',
    'martin',
    'lee',
    'perez',
    'thompson',
    'white',
    'harris',
    'sanchez',
    'clark',
    'ramirez',
    'lewis',
    'robinson',
    'walker',
    'young',
    'allen',
    'king',
    'wright',
    'scott',
    'torres',
    'nguyen',
    'hill',
    'flores',
    'green',
    'adams',
    'nelson',
    'baker',
    'hall',
    'rivera',
    'campbell',
    'mitchell',
    'carter',
    'roberts',
    'gomez',
    'phillips',
    'evans',
    'turner',
    'diaz',
    'parker',
    'cruz',
    'edwards',
    'collins',
    'reyes',
    'stewart',
    'morris',
    'morales',
    'murphy',
    'cook',
    'rogers',
    'gutierrez',
    'ortiz',
    'morgan',
    'cooper',
    'peterson',
    'bailey',
    'reed',
    'kelly',
    'howard',
    'ramos',
    'kim',
    'cox',
    'ward',
    'richardson',
    'watson',
    'brooks',
    'chavez',
    'wood',
    'james',
    'bennett',
    'gray',
    'mendoza',
    'ruiz',
    'hughes',
    'price',
    'alvarez',
    'castillo',
    'sanders',
    'patel',
    'myers',
    'long',
    'ross',
    'foster',
    'jimenez',
    'powell',
    'jenkins',
    'perry',
    'russell',
    'sullivan',
    'bell',
    'coleman',
    'butler',
    'henderson',
    'barnes',
    'gonzales',
    'fisher',
    'vasquez',
    'simmons',
    'romero',
    'jordan',
    'patterson',
    'alexander',
    'hamilton',
]

# Common email domains
domains = [
    'gmail.com',
    'yahoo.com',
    'hotmail.com',
    'outlook.com',
    'aol.com',
    'icloud.com',
    'protonmail.com',
    'mail.com',
    'yandex.com',
    'zoho.com',
    'fastmail.com',
    'tutanota.com',
    'gmx.com',
    'live.com',
    'msn.com',
    'comcast.net',
    'verizon.net',
    'att.net',
    'cox.net',
    'charter.net',
    'earthlink.net',
    'sbcglobal.net',
    'bellsouth.net',
    'roadrunner.com',
    'mail.ru',
    '163.com',
    'qq.com',
    'sina.com',
    'naver.com',
    'daum.net',
    'web.de',
    't-online.de',
    'orange.fr',
    'free.fr',
    'laposte.net',
    'virgilio.it',
    'libero.it',
    'tiscali.it',
    'alice.it',
    'tin.it',
    'bol.com.br',
    'uol.com.br',
    'ig.com.br',
    'terra.com.br',
    'globo.com',
    'rediffmail.com',
    'sify.com',
    'indiatimes.com',
    'in.com',
    'yahoo.co.in',
]


def generate_email():
    """Generate a random email address."""
    first = random.choice(first_names)
    last = random.choice(last_names)
    domain = random.choice(domains)

    # Different email format patterns
    patterns = [
        f"{first}.{last}",
        f"{first}{last}",
        f"{first}_{last}",
        f"{first}{last[0]}",
        f"{first[0]}.{last}",
        f"{first[0]}{last}",
        f"{first}{random.randint(1, 999)}",
        f"{first}.{last}{random.randint(1, 99)}",
        f"{first}_{last}{random.randint(1, 999)}",
        f"{last}.{first}",
        f"{last}{first}",
        f"{last}_{first}",
        f"{first}{random.randint(10, 9999)}",
        f"{first}.{random.randint(1, 99)}",
        f"{first}_{random.randint(1, 999)}",
    ]

    username = random.choice(patterns).lower()
    return f"{username}@{domain}"


def generate_unique_emails(count=3000):
    """Generate a list of unique email addresses."""
    emails = set()

    while len(emails) < count:
        email = generate_email()
        emails.add(email)

        # Print progress every 500 emails
        if len(emails) % 500 == 0:
            print(f"Generated {len(emails)} emails...")

    return sorted(list(emails))


if __name__ == "__main__":
    print("Generating 3000 unique email addresses...")
    emails = generate_unique_emails(3000)

    # Write to file
    output_file = "/Users/igoreremin/repo/text_renderer/tlr/text/email_text.txt"
    with open(output_file, 'w') as f:
        for email in emails:
            f.write(email + '\n')

    print(
        f"Successfully generated {len(emails)} unique emails and saved to {output_file}"
    )
    print("\nFirst 10 emails:")
    for i, email in enumerate(emails[:10]):
        print(f"{i+1}. {email}")
